---
resources:
- name: hello
  type: git
  source:
    uri: https://github.com/marronn/concourse.git
- name: result
  type: git
  source:
    uri: git@gist.github.com:0fe9810a3b0e5bdf7ef9e30a56636913.git 
    private_key: {{github-private-key}}
    branch: master

jobs:
- name: job-hello
  public: true
  plan:
  - get: hello
    trigger: true
  - get: result
  - task: run-hello
    file: hello/hello.yml
  - task: commit-log
    file: hello/commit-log.yml
  - put: result
    params:
      repository: updated-result
